### ISSUE TITLE
State of Port

### ISSUE THREAD

**Issue by paulushub** [NightOwl888/ICU4N#1]
What is the state of this ICUJ port and is a release scheduled?

**Comment by NightOwl888** [comment]
I have updated the [README](https://github.com/NightOwl888/ICU4N/blob/master/README.md) with some information about the state of the port. I just published an [alpha on NuGet](https://www.nuget.org/packages?q=ICU4N).

This project was started to support Lucene.Net, so the priorities were driven by the features that Lucene used, and these are the pieces that are the most stable.

1. BreakIterator
2. Collator
3. Transliterator
4. Normalizer2
5. UnicodeSet
6. UProperty
7. UScript

As ICU4J is a pretty big project, this port is only being worked on by one person, and there are many Java-like features that ought to be changed to be more .NET-like I can't really give an anticipated date on a stable release. However, using the above features should work fine for most applications provided you are okay with an API that will likely change between releases.

**Comment by paulushub** [comment]
Thanks for finally replying to this post! I was working on a Java port Google font library (sfntly), and a sample uses the ICU-J.
I was able to use the current version to run the sample successfully, but wished for a NuGet version since the size of the library is huge.
This alpha release will help a lot, thank you.

**Comment by NightOwl888** [comment]
Great. I am closing this issue, as the question has been addressed.
